type: object
properties:
  params:
    type: object
  input:
    type: object
    additionalProperties: false
    required:
    - timestampMask
    - processName
    - eventlogInputColumns
    properties:
      timestampMask:
        type: string
      processName:
        type: string
      eventlogInputColumns:
        type: object
        additionalProperties: false

        required:
        - caseId
        - activity
        anyOf: [
        {"required": ["startTimestamp"]},
        {"required": ["endTimestamp"]}
        ]
        properties:
          caseId:
            type: string
          activity:
            type: string
          endTimestamp:
            type: string
          startTimestamp:
            type: string
          resource:
            type: string
