input:
  timestampMask: "%Y-%m-%dT%H:%M:%S"
  processName: process
  eventlogInputColumns:
    caseId: case_id
    activity: activity
    endTimestamp: end_time
    startTimestamp: start_time
    resource: resource
