input:
  timestampMask: "%Y-%m-%dT%H:%M:%S"
  processName: p2p_short
  eventlogInputColumns:
    caseId: case_id
    activity: Activity
    endTimestamp: end_time
    startTimestamp: start_time
    resource: Resource
